# Metadata

language_name = "Български"
translated_by = "Превод: AI"
author = "Създадено от Kierownik223"

# Header

home = "Начало"
settings = "Настройки"
log_in = "Вход"
manage_account = "Управление на акаунт"
admin = "Админ панел"
log_out = "Изход"

# Settings

sync_settings = "Синхронизиране на настройки"
sync_success = "Настройките бяха успешно запазени."
fetch_settings = "Зареди настройки"
fetch_success = "Настройките бяха успешно заредени!"
language = "Език"
theme = "Тема"
change_lang = "Смени езика (НОВО!)"
change_theme = "Смени тема"
theme_default = "По подразбиране"
theme_darkblu = "Тъмносиня тема"
theme_greenish = "Зеленикава тема"
theme_antique = "Антична (оригинална) тема"
plain = "Обикновен HTML"
enable = "Активирай"
disable = "Деактивирай"
hires = "Икони с висока резолюция"
smallhead = "Малко лого в заглавката"
dont_override_settings = "Не презаписвай настройките"
save_settings = "Запази настройките"
reset_settings = "Нулиране на настройките"

# Files

readme = "Информация"
download = "Изтегли"
file = "Файл"
folder = "Папка"
archive = "Архив"
zipviewer_title = "ZIP преглед"
zip_file = "ZIP файл"
mdreader_title = "MD четец"
reading_markdown = "Четене на файл"
file_details = "Детайли за файла"
file_name = "Име на файл"
file_size = "Размер на файл"
file_downloads = "Изтегляния"
print = "Принтирай"
viewing_zip = "Преглед на ZIP файл"
watching = "Гледане на файл"

# Uploader

uploader = "Качвач"
upload = "Качи"
select_file = "Изберете файл"
upload_success = "успешно качен!"
upload_error = "Възникна грешка при качването на файла."
uploader_title = "Качвач на файлове"
target_dir = "Целева директория"
target_placeholder = "Оставете празно за /uploads/"
max_size = "Максималният разрешен размер на файла е 100MB."
select_folder = "Изберете папка"
browse = "Преглед"
select_files = "Изберете файлове за качване."
uploading = "Качване"

# Account

username = "Потребителско име"
password = "Парола"
invalid_info = "Невалидно потребителско име или парола."
log_in_with_marmak = "Влез с MARMAK акаунт™"
welcome = "Здравей"
tip = "Съвет"
settings_tip1 = "Ако искате да запазите текущите настройки, отидете на"
settings_tip2 = "и активирайте „Не презаписвай настройките“."

# Admin

usage = "Използване"
disk_usage = "Използване на диска"
sysinfo = "Информация за сървъра"
memory_usage = "Използване на паметта"
system = "Система"
kernel_version = "Версия на ядрото"
hostname = "Име на хоста"

# Audio player

listening = "Слушане на файл"
album = "Албум"
year = "Година"
genre = "Жанр"
album_cover = "Корицата на албума"

# File deletion

delete_success = "успешно премахнато!"
delete_confirmation = "Сигурни ли сте, че искате да изтриете"
delete = "Изтрий"

# Errors

error = "Грешка"
not_found = "Не е намерено"
error_400 = "Клиентът изпрати невалидна заявка. Моля, опитайте отново."
error_404 = "Заявеният ресурс не може да бъде намерен. Проверете URL и опитайте отново."
error_50x = "Вътрешна сървърна грешка възникна. Моля, докладвайте това."
error_403 = "Нямате достъп до този ресурс. Моля, влезте с потребител с по-високи права."
no_details = "Няма налични подробности!"
no_video = "Вашият браузър не поддържа видео елемента."
no_audio = "Вашият браузър не поддържа аудио елемента."
upload_parse_error = "качено, но отговорът не може да бъде обработен."
upload_failed_status = "неуспешно със статус"
upload_failed_network = "качването не успя поради мрежова грешка."
error_occured = "Възникна грешка:"
error_deleting = "Възникна грешка при изтриването на файла."
directory_not_empty = "Тази директория не е празна!"

# Generic UI strings

ok = "ОК"
cancel = "Отказ"
others = "други"
cookie_notice = "Използваме бисквитки само за съхранение на потребителски предпочитания. Ако не желаете да ги използваме, не променяйте нищо на тази страница."
