# Metadata

language_name = "Bosanski"
translated_by = "Prevod: AI"
author = "Izradio Kierownik223"

# Header

home = "Početna"
settings = "Postavke"
log_in = "Prijava"
manage_account = "Upravljaj računom"
admin = "Admin panel"
log_out = "Odjava"

# Settings

sync_settings = "Sinhronizuj postavke"
sync_success = "Postavke uspješno sačuvane."
fetch_settings = "Preuzmi postavke"
fetch_success = "Postavke uspješno preuzete!"
language = "Jezik"
theme = "Tema"
change_lang = "Promijeni jezik (NOVO!)"
change_theme = "Promijeni temu"
theme_default = "Podrazumijevana tema"
theme_darkblu = "Tamno plava tema"
theme_greenish = "Zelenkasta tema"
theme_antique = "Antička (originalna) tema"
plain = "Običan HTML"
enable = "Omogući"
disable = "Onemogući"
hires = "Ikone visoke rezolucije"
smallhead = "Mali logo u zaglavlju"
dont_override_settings = "Ne prepisuj postavke"
save_settings = "Sačuvaj postavke"

# Files

readme = "Informacije"
download = "Preuzmi"
file = "Datoteka"
folder = "Fascikla"
archive = "Arhiva"
zipviewer_title = "ZIP preglednik"
zip_file = "ZIP datoteka"
mdreader_title = "MD čitač"
reading_markdown = "Čitanje datoteke"
file_details = "Detalji o datoteci"
file_name = "Naziv datoteke"
file_size = "Veličina datoteke"
file_downloads = "Preuzimanja"
print = "Štampaj"
viewing_zip = "Pregled ZIP datoteke"
watching = "Gledanje datoteke"

# Uploader

uploader = "Učitavač"
upload = "Otpremi"
select_file = "Izaberite datoteku"
upload_success = "uspješno otpremljena!"
upload_error = "Došlo je do greške pri otpremanju datoteke."
uploader_title = "Učitavač datoteka"
target_dir = "Ciljni direktorij"
target_placeholder = "Ostavite prazno za /uploads/"
max_size = "Maksimalna dozvoljena veličina datoteke je 100MB."
select_folder = "Izaberite fasciklu"
browse = "Pregledaj"
select_files = "Izaberite datoteke za otpremanje."
uploading = "Otpremanje"

# Account

username = "Korisničko ime"
password = "Lozinka"
invalid_info = "Neispravno korisničko ime ili lozinka."
log_in_with_marmak = "Prijavite se putem MARMAK naloga™"
welcome = "Zdravo"
tip = "Savjet"
settings_tip1 = "Ako želite zadržati trenutne postavke, idite na"
settings_tip2 = "i omogućite \"Ne prepisuj postavke\"."

# Admin

usage = "Iskorištenost"
disk_usage = "Iskorištenost diska"
sysinfo = "Informacije o serveru"
memory_usage = "Iskorištenost memorije"
system = "Sistem"
kernel_version = "Verzija kernela"
hostname = "Naziv hosta"

# Audio player

listening = "Slušanje datoteke"
album = "Album"
year = "Godina"
genre = "Žanr"
album_cover = "Naslovnica albuma"

# File deletion

delete_success = "uspješno obrisano!"
delete_confirmation = "Jeste li sigurni da želite obrisati"
delete = "Obriši"

# Errors

error = "Greška"
not_found = "Nije pronađeno"
error_400 = "Klijent je poslao neispravan zahtjev. Pokušajte ponovo."
error_404 = "Traženi resurs nije pronađen. Provjerite URL i pokušajte ponovo."
error_50x = "Došlo je do interne greške servera. Molimo prijavite ovo."
error_403 = "Trenutno nemate pristup ovom resursu. Prijavite se kao korisnik s višim privilegijama."
no_details = "Nema dostupnih detalja!"
no_video = "Vaš pretraživač ne podržava video element."
no_audio = "Vaš pretraživač ne podržava audio element."
upload_parse_error = "otpremljeno, ali odgovor nije moguće parsirati."
upload_failed_status = "neuspjeh sa statusom"
upload_failed_network = "otpremanje nije uspjelo zbog mrežne greške."
error_occured = "Došlo je do greške:"
error_deleting = "Došlo je do greške prilikom brisanja datoteke."
directory_not_empty = "Ovaj direktorij nije prazan!"

# Generic UI strings

ok = "U redu"
cancel = "Otkaži"
others = "ostali"
