# Metadata

language_name = "Kaszëbsczi"
translated_by = "Tłomaczenié: Maszina"
author = "Ùsôdzony przez Kierownik223"

# Header

home = "Domô"
settings = "Ùstawiënkò"
log_in = "Zalogùjë sã"
manage_account = "Zarzãdzë kùntã"
admin = "Panel administracyji"
log_out = "Wëlogùjë sã"

# Settings

sync_settings = "Sënkronizëjë ùstawiënka"
sync_success = "Ùstawiënka òstë sã zapiśóné."
fetch_settings = "Pòbrac ùstawiënka"
fetch_success = "Ùstawiënka pòbróné!"
language = "Jãzëk"
theme = "Szablón"
change_lang = "Zmien jãzëk (NOWÉ!)"
change_theme = "Zmien szablón"
theme_default = "Domësny szablón"
theme_darkblu = "Mroczno-niebiesczi szablón"
theme_greenish = "Zielônawy szablón"
theme_antique = "Stôrzé (òriginałné)"
plain = "Prosté HTML"
enable = "Włączë"
disable = "Wëłączë"
hires = "Wëżokòrozlëszczi ikònë"
smallhead = "Môłô lëżba w gùłówce"
dont_override_settings = "Nie nadpisëwôj ùstawiënkòw"
save_settings = "Zapisz ùstawiënka"

# Files

readme = "Informacëjô"
download = "Szëgnë"
file = "Plik"
folder = "Katalog"
archive = "Archiwum"
zipviewer_title = "Òbieracz ZIP"
zip_file = "Plik ZIP"
mdreader_title = "Czëtôcz MD"
reading_markdown = "Czëtôjã plik"
file_details = "Detale plika"
file_name = "Miono plika"
file_size = "Wëlkòsc plika"
file_downloads = "Szëgnãcë"
print = "Drëkni"
viewing_zip = "Òbiéranié ZIP-a"
watching = "Òbiéranié plika"

# Uploader

uploader = "Wësëłôcz plików"
upload = "Wësëłôj"
select_file = "Wëbierz plik"
upload_success = "został wësłóny!"
upload_error = "Wëstąpił feler przë wësëłaniô plika."
uploader_title = "Wësëłôcz plików"
target_dir = "Môlowóné katalog"
target_placeholder = "Zostów pusté dlô /uploads/"
max_size = "Maximôlnô wëlkòsc plika: 100MB."
select_folder = "Wëbierz katalog"
browse = "Przeglądôj"
select_files = "Wëbierz plikë do wësłaniô."
uploading = "Wësëłanié"

# Account

username = "Brëkòwnik"
password = "Hasło"
invalid_info = "Lëché miono abò hasło."
log_in_with_marmak = "Zalogùjë sã z MARMAK Rëkùnkã&trade;"
welcome = "Witaj"
tip = "Rada"
settings_tip1 = "Jeżlë chcesz zatrzëmac aktualné ùstawiënka, farëj do"
settings_tip2 = "a włączë \"Nie nadpisëwôj ùstawiënków\"."

# Admin

usage = "Brëkòwanié"
disk_usage = "Brëkòwanié diskù"
sysinfo = "Infòrmacëjô ò serwerze"
memory_usage = "Brëkòwanié pamięcë"
system = "System"
kernel_version = "Wersjô jądra"
hostname = "Miono serwera"

# Audio player

listening = "Słëchôjã plika"
album = "Albùm"
year = "Rok"
genre = "Żanr"
album_cover = "Òbrazek albùmu"

# File deletion

delete_success = "został rëmniãty!"
delete_confirmation = "Jis jiste, że chcesz rëmnąc"
delete = "Rëmnij"

# Errors

error = "Feler"
not_found = "Nie nalezioné"
error_400 = "Klijent pòsłał nieprawidłową żądanié. Spróbùjë znowa."
error_404 = "Żądané źródło nie je nalézioné. Sprawdzë URL i spróbùjë znowa."
error_50x = "Wënkł feler serwera. Proszã zgłosëc do nas."
error_403 = "Ni môsz dostãpù do ti zasobu. Wlogùjë sã jako administratòr."
no_details = "Ni mô detali!"
no_video = "Twój przeglãdôcz nie wspierô elemenatu video."
no_audio = "Twój przeglãdôcz nie wspierô elemenatu audio."
upload_parse_error = "został wësłóny, ale ni mòże bëł òdczytóny."
upload_failed_status = "nie darziło sã ze statusem"
upload_failed_network = "wësłanié nie darziło sã przez felera z netã."
error_occured = "Wëstąpił feler:"
error_deleting = "Wëstąpił feler przë rëmnëniô plika."
directory_not_empty = "Ti katalog nie je pùsté!"

# Generic UI strings

ok = "W porzãdku"
cancel = "Anulëjë"
others = "jiné"
