home = "Dom"
translated_by = "Przetłomaczenié: Kòmpùter"
author = "Zrobione przez Kierownik223"
readme = "Wëdowiédzë"
download = "Pòbiérzë"
zipviewer_title = "Przëglo w ZIP-ach"
mdreader_title = "Przëglo w MD"
zip_file = "ZIP lopk"
archive = "Archiwùm"
reading_markdown = "Czëtanié lopka"
not_found = "Né nalazłò"
file_details = "Detale lopka"
file_name = "Miono lopka"
file_size = "Wjelëzna lopka"
file_downloads = "Pòbiéraniô"
error = "Fela"
language = "Mòwa"
theme = "Mòtëw"
change_lang = "Zmieni mòwã (NOWÉ!)"
change_theme = "Zmieni mòtëw"
theme_default = "Domëszlny mòtëw"
theme_darkblu = "Czôrny-niebiesczi mòtëw"
theme_greenish = "Zéłonawy mòtëw"
theme_antique = "Antik (òrigënalny) mòtëw"
plain = "Czësti HTML"
normal_mode = "Normôlny mòd"
file = "lopk"
folder = "Katalog"
uploader = "Ladowc lopków"
upload = "Ladëjë"
select_file = "Wëbiérz lopk"
upload_success = "załadowóné sztëcznie!"
upload_error = "Nastôła fela przy ladowaniô lopka."
uploader_title = "Ladowc lopków"
admin = "Pòrtôl admina"
username = "Miono brëkòwnika"
password = "Hasło"
log_in = "Wlogùjë sã"
log_out = "Wëlogùjë sã"
invalid_info = "Błãdné miono brëkòwnika abò hasło."
log_in_with_marmak = "Wlogùjë sã z MARMAK Account&trade;"
welcome = "Cześć"
sync_settings = "Sënkronizëjë nastôwë"
sync_success = "Nastôwë zapisóné sztëcznie."
dont_override_settings = "Nie nadpisëjë nastôwów"
settings = "Nastôwë"
save_settings = "Zapiszë nastôwë"
hires = "Ikònë w wëżôszé rozdzielczoscë"
smallhead = "Môłé logo na górze"
enable = "Zôłãczë"
disable = "Wëłãczë"
target_dir = "Miejsce docelòwé"
target_placeholder = "Òstaw pùsté dlô /uploads/"
fetch_settings = "Biérzë nastôwë"
fetch_success = "Nastôwë biérzoné sztëcznie!"
print = "Drëkùjë"
error_400 = "Klient słał fëszne żądanié. Spróbùjë jesz wëd."
error_404 = "Né mòże nalézc pòdónégò żëdła. Sprawdë adres ë spróbùjë jesz wëd."
error_50x = "Nastôł wëdowi felôr serwera. Proszã zgłoszë to."
error_403 = "Ni môsz teraz dostãpu do tegò resùrsu. Proszã sã zalogòwac jakno ùżëkòwnik z wiãkszimë pòdprzëwilejami."
max_size = "Maksimôlô wëlëzna lopka je 100MB."
usage = "Brëkòwanié"
disk_usage = "Brëkòwanié diskù"
sysinfo = "Wëdowiédzë ò serwerze"
manage_account = "Zôrzãdzanié kontã"
tip = "Wënôzk"
settings_tip1 = "Jaczë chcesz trzimac swojë nastôwë, idz do"
settings_tip2 = "ë zôłãczë \"Nie nadpisëjë nastôwów\"."
memory_usage = "Brëkòwanié pamiãcë"
system = "Sistém"
kernel_version = "Wersëjô jądra"
hostname = "Miono serwera"
browse = "Przëglońdzë"
select_folder = "Wëbiérz katalog"
ok = "OK"
cancel = "Rëchëj sã"
viewing_zip = "Przëglo w ZIP-ach"
no_details = "Brak detali!"
watching = "Przëglo lopka"
no_video = "Twòj przëglońdzôrz nie òbsłëżë wëdowi element wideo."
others = "inë"
select_files = "Wëbiérz lopczi do nahraniô."
uploading = "Nahrëwanié"
upload_parse_error = "nahróné, ale òdpòwiesc nie mògła bëc sparslowónô."
upload_failed_status = "nie darzëło sã z statusã"
upload_failed_network = "nahranié nie darzëło sã przez felã siecë."
listening = "Słëchanié lopka"
no_audio = "Twój przeglãdnik nie wspiarô elementu audio."
album = "Albùm"
year = "Rôk"
genre = "Żanr"
album_cover = "Ôbrôzk albùmu"
