# Metadata

language_name = "Deutsch"
translated_by = "Übersetzung: Maschine"
author = "Erstellt von Kierownik223"

# Header

home = "Startseite"
settings = "Einstellungen"
log_in = "Anmelden"
manage_account = "Konto verwalten"
admin = "Adminbereich"
log_out = "Abmelden"

# Settings

sync_settings = "Einstellungen synchronisieren"
sync_success = "Einstellungen erfolgreich gespeichert."
fetch_settings = "Einstellungen abrufen"
fetch_success = "Einstellungen erfolgreich abgerufen!"
language = "Sprache"
theme = "Design"
change_lang = "Sprache ändern (NEU!)"
change_theme = "Design ändern"
theme_default = "Standarddesign"
theme_darkblu = "Dunkelblaues Design"
theme_greenish = "Grünliches Design"
theme_antique = "Antik (originales Design)"
plain = "Einfaches HTML"
enable = "Aktivieren"
disable = "Deaktivieren"
hires = "Hochauflösende Symbole"
smallhead = "Kleines Header-Logo"
dont_override_settings = "Einstellungen nicht überschreiben"
save_settings = "Einstellungen speichern"
reset_settings = "Einstellungen zurücksetzen"
viewers = "Dateidetailbetrachter"

# Files

readme = "Information"
download = "Download"
file = "Datei"
folder = "Dateiordner"
archive = "Archiv"
zipviewer_title = "ZIP-Betrachter"
zip_file = "ZIP-Datei"
mdreader_title = "MD-Reader"
reading_markdown = "Datei wird gelesen"
file_details = "Dateidetails"
file_name = "Dateiname"
file_size = "Dateigröße"
file_downloads = "Downloads"
print = "Drucken"
viewing_zip = "ZIP-Datei anzeigen"
watching = "Datei ansehen"
download_zip = "ZIP herunterladen"
preparing_zip = "ZIP wird vorbereitet..."
rename = "Umbenennen"
rename_success = "Erfolgreich umbenannt!"
new_name = "Neuer Name"
error_renaming = "Beim Umbenennen ist ein Fehler aufgetreten"

# Uploader

uploader = "Uploader"
upload = "Hochladen"
select_file = "Datei auswählen"
upload_success = "erfolgreich hochgeladen!"
upload_error = "Beim Hochladen der Datei ist ein Fehler aufgetreten."
uploader_title = "Datei-Uploader"
target_dir = "Zielverzeichnis"
target_placeholder = "Leer lassen für /uploads/"
max_size = "Maximale Dateigröße beträgt 100 MB."
select_folder = "Ordner auswählen"
browse = "Durchsuchen"
select_files = "Dateien auswählen."
uploading = "Hochladen"
login_to_continue = "Melden Sie sich an, um fortzufahren zu"

# Account

username = "Benutzername"
password = "Passwort"
invalid_info = "Ungültiger Benutzername oder Passwort."
log_in_with_marmak = "Mit einem MARMAK-Konto anmelden&trade;"
welcome = "Hallo"
tip = "Tipp"
settings_tip1 = "Wenn du deine aktuellen Einstellungen behalten möchtest, gehe zu"
settings_tip2 = "und aktiviere „Einstellungen nicht überschreiben“."

# Admin

usage = "Nutzung"
disk_usage = "Speicherverbrauch"
sysinfo = "Serverinformationen"
memory_usage = "Speicherauslastung"
system = "System"
kernel_version = "Kernel-Version"
hostname = "Hostname"

# Audio player

listening = "Datei wird abgespielt"
album = "Album"
year = "Jahr"
genre = "Genre"
album_cover = "Albumcover"

# File deletion

delete_success = "erfolgreich entfernt!"
delete_confirmation = "Bist du sicher, dass du löschen möchtest"
delete = "Löschen"

# Errors

error = "Fehler"
not_found = "Nicht gefunden"
error_400 = "Ungültige Anfrage gesendet. Bitte erneut versuchen."
error_404 = "Ressource nicht gefunden. URL überprüfen und erneut versuchen."
error_50x = "Interner Serverfehler. Bitte melden."
error_403 = "Kein Zugriff auf diese Ressource. Höher privilegierten Benutzer einloggen."
no_details = "Keine Details verfügbar!"
no_video = "Dein Browser unterstützt das Videoelement nicht."
no_audio = "Dein Browser unterstützt das Audioelement nicht."
upload_parse_error = "hochgeladen, aber Antwort konnte nicht verarbeitet werden."
upload_failed_status = "fehlgeschlagen mit Status"
upload_failed_network = "Hochladen fehlgeschlagen aufgrund eines Netzwerkfehlers."
error_occured = "Ein Fehler ist aufgetreten:"
error_deleting = "Fehler beim Löschen der Datei aufgetreten."
directory_not_empty = "Dieses Verzeichnis ist nicht leer!"
upload_not_supported = "Der JavaScript-Uploader wird von diesem Browser nicht unterstützt."

# Generic UI strings

ok = "OK"
cancel = "Abbrechen"
others = "andere"
cookie_notice = "Wir verwenden Cookies nur, um Benutzereinstellungen zu speichern. Wenn Sie diese nicht verwenden möchten, ändern Sie nichts auf dieser Seite."
