home = "Startseite"
translated_by = "Übersetzung: Machine"
author = "Erstellt von Kierownik223"
readme = "Informationen"
download = "Herunterladen"
zipviewer_title = "ZIP-Viewer"
mdreader_title = "MD-Reader"
zip_file = "ZIP-Datei"
archive = "Archiv"
reading_markdown = "Datei wird gelesen"
not_found = "Nicht gefunden"
file_details = "Dateidetails"
file_name = "Dateiname"
file_size = "Dateigröße"
file_downloads = "Downloads"
error = "Fehler"
language = "Sprache"
theme = "Thema"
change_lang = "Sprache ändern (NEU!)"
change_theme = "Thema ändern"
theme_default = "Standardthema"
theme_darkblu = "Dunkelblaues Thema"
theme_greenish = "Grünliches Thema"
theme_antique = "Antikes (originales) Thema"
plain = "Einfaches HTML"
normal_mode = "Normaler Modus"
file = "Datei"
folder = "Dateiordner"
uploader = "Uploader"
upload = "Hochladen"
select_file = "Datei auswählen"
upload_success = "erfolgreich hochgeladen!"
upload_error = "Beim Hochladen der Datei ist ein Fehler aufgetreten."
uploader_title = "Datei-Uploader"
admin = "Admin-Panel"
username = "Benutzername"
password = "Passwort"
log_in = "Anmelden"
log_out = "Abmelden"
invalid_info = "Ungültiger Benutzername oder Passwort."
log_in_with_marmak = "Mit einem MARMAK-Konto anmelden&trade;"
welcome = "Hallo"
sync_settings = "Einstellungen synchronisieren"
sync_success = "Einstellungen erfolgreich gespeichert."
dont_override_settings = "Einstellungen nicht überschreiben"
settings = "Einstellungen"
save_settings = "Einstellungen speichern"
hires = "Hochauflösende Symbole"
smallhead = "Kleines Header-Logo"
enable = "Aktivieren"
disable = "Deaktivieren"
target_dir = "Zielverzeichnis"
target_placeholder = "Leer lassen für /uploads/"
fetch_settings = "Einstellungen abrufen"
fetch_success = "Einstellungen erfolgreich abgerufen!"
print = "Drucken"
error_400 = "Der Client hat eine ungültige Anfrage gesendet. Bitte versuchen Sie es erneut."
error_404 = "Die angeforderte Ressource konnte nicht gefunden werden. Bitte überprüfen Sie die URL und versuchen Sie es erneut."
error_50x = "Ein interner Serverfehler ist aufgetreten. Bitte melden Sie uns dies."
max_size = "Maximale Dateigröße beträgt 100 MB."
usage = "Verwendung"
disk_usage = "Festplattennutzung"
sysinfo = "Serverinformationen"
manage_account = "Konto verwalten"
tip = "Tipp"
settings_tip1 = "Wenn Sie Ihre aktuellen Einstellungen beibehalten möchten, gehen Sie zu"
settings_tip2 = "und aktivieren Sie \"Einstellungen nicht überschreiben\"."
memory_usage = "Speichernutzung"
system = "System"
kernel_version = "Kernel-Version"
hostname = "Hostname"
browse = "Durchsuchen"
select_folder = "Ordner auswählen"
ok = "OK"
cancel = "Abbrechen"
viewing_zip = "ZIP-Datei anzeigen"
no_details = "Keine Details verfügbar!"
watching = "Datei ansehen"
no_video = "Ihr Browser unterstützt das Videoelement nicht."
others = "andere"
select_files = "Dateien zum Hochladen auswählen."
uploading = "Wird hochgeladen"
upload_parse_error = "hochgeladen, aber Antwort konnte nicht analysiert werden."
upload_failed_status = "fehlgeschlagen mit Status"
upload_failed_network = "Hochladen wegen Netzwerkfehler fehlgeschlagen."
