# Metadata

language_name = "Eesti"
translated_by = "Tõlge: AI"
author = "Teinud Kierownik223"

# Header

home = "Kodu"
settings = "Seaded"
log_in = "Logi sisse"
manage_account = "Halda kontot"
admin = "Admin paneel"
log_out = "Logi välja"

# Settings

sync_settings = "Sünkrooni seaded"
sync_success = "Seaded edukalt salvestatud."
fetch_settings = "Laadi seaded"
fetch_success = "Seaded edukalt laaditud!"
language = "Keel"
theme = "Teema"
change_lang = "Vaheta keelt (UUS!)"
change_theme = "Vaheta teemat"
theme_default = "Vaiketema"
theme_darkblu = "Tume sinine teema"
theme_greenish = "Rohekas teema"
theme_antique = "Antiikne (algne) teema"
plain = "Lihtne HTML"
enable = "Luba"
disable = "Keela"
hires = "Kõrge resolutsiooniga ikoonid"
smallhead = "Väike päise logo"
dont_override_settings = "Ära ülekirjuta seadeid"
save_settings = "Salvesta seaded"
reset_settings = "Lähtesta seaded"

# Files

readme = "Info"
download = "Laadi alla"
file = "Fail"
folder = "Kaust"
archive = "Arhiiv"
zipviewer_title = "ZIP vaataja"
zip_file = "ZIP fail"
mdreader_title = "MD lugeja"
reading_markdown = "Loeb faili"
file_details = "Faili üksikasjad"
file_name = "Faili nimi"
file_size = "Faili suurus"
file_downloads = "Allalaadimised"
print = "Prindi"
viewing_zip = "Vaadates ZIP faili"
watching = "Vaadates faili"

# Uploader

uploader = "Laadija"
upload = "Laadi üles"
select_file = "Vali fail"
upload_success = "laaditi edukalt üles!"
upload_error = "Tõrge faili üleslaadimisel."
uploader_title = "Faili üleslaadija"
target_dir = "Sihtkaust"
target_placeholder = "Jäta tühjaks /uploads/"
max_size = "Maksimaalne failisuurus on 100MB."
select_folder = "Vali kaust"
browse = "Sirvi"
select_files = "Vali failid üleslaadimiseks."
uploading = "Laadib üles"

# Account

username = "Kasutajanimi"
password = "Parool"
invalid_info = "Vigane kasutajanimi või parool."
log_in_with_marmak = "Logi sisse MARMAK kontoga™"
welcome = "Tere"
tip = "Nõuanne"
settings_tip1 = "Kui soovid hoida oma praeguseid seadeid, mine"
settings_tip2 = "ja lülita sisse \"Ära ülekirjuta seadeid\"."

# Admin

usage = "Kasutus"
disk_usage = "Ketta kasutus"
sysinfo = "Serveri info"
memory_usage = "Mälu kasutus"
system = "Süsteem"
kernel_version = "Kernel versioon"
hostname = "Hosti nimi"

# Audio player

listening = "Kuulab faili"
album = "Album"
year = "Aasta"
genre = "Žanr"
album_cover = "Albumi kaas"

# File deletion

delete_success = "eemaldatud edukalt!"
delete_confirmation = "Oled sa kindel, et soovid selle kustutada?"
delete = "Kustuta"

# Errors

error = "Viga"
not_found = "Ei leitud"
error_400 = "Klient saatis vale päringu. Palun proovi uuesti."
error_404 = "Taotletud ressurssi ei leitud. Kontrolli URLi ja proovi uuesti."
error_50x = "Serveris toimus sisemine viga. Palun teata meile."
error_403 = "Sul pole ligipääsu sellele ressursile. Palun logi sisse kõrgema õigusega kasutajana."
no_details = "Üksikasjad puuduvad!"
no_video = "Sinu brauser ei toeta video elementi."
no_audio = "Sinu brauser ei toeta audio elementi."
upload_parse_error = "laaditi üles, kuid vastust ei saanud töödelda."
upload_failed_status = "ebaõnnestus olekuga"
upload_failed_network = "üleslaadimine nurjus võrgu vea tõttu."
error_occured = "Tekkis viga:"
error_deleting = "Tekkis viga faili kustutamisel."
directory_not_empty = "See kataloog ei ole tühi!"

# Generic UI strings

ok = "OK"
cancel = "Tühista"
others = "teised"
cookie_notice = "Kasutame küpsiseid ainult kasutajaseadete salvestamiseks. Kui sa ei soovi neid kasutada, ära muuda sellel lehel midagi."
