# Metadata

language_name = "Magyar"
translated_by = "Fordítás: AI"
author = "Készítette: Kierownik223"

# Header

home = "Főoldal"
settings = "Beállítások"
log_in = "Bejelentkezés"
manage_account = "Fiók kezelése"
admin = "Admin panel"
log_out = "Kijelentkezés"

# Settings

sync_settings = "Beállítások szinkronizálása"
sync_success = "A beállítások sikeresen elmentve."
fetch_settings = "Beállítások lekérése"
fetch_success = "A beállítások sikeresen betöltve!"
language = "Nyelv"
theme = "Téma"
change_lang = "Nyelv módosítása (ÚJ!)"
change_theme = "Téma módosítása"
theme_default = "Alapértelmezett téma"
theme_darkblu = "Sötétkék téma"
theme_greenish = "Zöldes téma"
theme_antique = "Antik (eredeti) téma"
plain = "Egyszerű HTML"
enable = "Engedélyezés"
disable = "Letiltás"
hires = "Nagy felbontású ikonok"
smallhead = "Kis fejléc logó"
dont_override_settings = "Beállítások ne íródjanak felül"
save_settings = "Beállítások mentése"
reset_settings = "Beállítások visszaállítása"

# Files

readme = "Információ"
download = "Letöltés"
file = "Fájl"
folder = "Fájlmappa"
archive = "Archívum"
zipviewer_title = "ZIP megtekintő"
zip_file = "ZIP fájl"
mdreader_title = "MD olvasó"
reading_markdown = "Fájl megtekintése"
file_details = "Fájl részletei"
file_name = "Fájlnév"
file_size = "Fájlméret"
file_downloads = "Letöltések"
print = "Nyomtatás"
viewing_zip = "ZIP fájl megtekintése"
watching = "Fájl megtekintése"

# Uploader

uploader = "Feltöltő"
upload = "Feltöltés"
select_file = "Válasszon fájlt"
upload_success = "sikeresen feltöltve!"
upload_error = "Hiba történt a fájl feltöltése közben."
uploader_title = "Fájlfeltöltő"
target_dir = "Célkönyvtár"
target_placeholder = "Hagyja üresen a /uploads/ könyvtárhoz"
max_size = "A maximálisan engedélyezett fájlméret 100MB."
select_folder = "Mappa kiválasztása"
browse = "Tallózás"
select_files = "Válassza ki a feltölteni kívánt fájlokat."
uploading = "Feltöltés folyamatban"

# Account

username = "Felhasználónév"
password = "Jelszó"
invalid_info = "Érvénytelen felhasználónév vagy jelszó."
log_in_with_marmak = "Bejelentkezés MARMAK-fiókkal&trade;"
welcome = "Üdv"
tip = "Tipp"
settings_tip1 = "Ha meg akarja őrizni jelenlegi beállításait, menjen ide:"
settings_tip2 = "és engedélyezze a \"Beállítások ne íródjanak felül\" opciót."

# Admin

usage = "Használat"
disk_usage = "Lemezhasználat"
sysinfo = "Szerverinformáció"
memory_usage = "Memóriahasználat"
system = "Rendszer"
kernel_version = "Kernel verzió"
hostname = "Gépnév"

# Audio player

listening = "Fájl hallgatása"
album = "Album"
year = "Év"
genre = "Műfaj"
album_cover = "Album borító"

# File deletion

delete_success = "sikeresen eltávolítva!"
delete_confirmation = "Biztosan törölni szeretné:"
delete = "Törlés"

# Errors

error = "Hiba"
not_found = "Nem található"
error_400 = "A kliens érvénytelen kérést küldött. Kérjük, próbálja újra."
error_404 = "A kért erőforrás nem található. Ellenőrizze az URL-t és próbálja újra."
error_50x = "Belső szerverhiba történt. Kérjük, jelezze nekünk."
error_403 = "Jelenleg nincs hozzáférése ehhez az erőforráshoz. Jelentkezzen be magasabb jogosultságú felhasználóként."
no_details = "Nincs elérhető részlet!"
no_video = "A böngészője nem támogatja a videó elemet."
no_audio = "A böngészője nem támogatja az audio elemet."
upload_parse_error = "feltöltve, de a válasz nem volt értelmezhető."
upload_failed_status = "sikertelen ezzel az állapottal:"
upload_failed_network = "a feltöltés hálózati hiba miatt meghiúsult."
error_occured = "Hiba történt:"
error_deleting = "Hiba történt a fájl törlése közben."
directory_not_empty = "Ez a mappa nem üres!"
upload_not_supported = "A JavaScript feltöltés nem támogatott ebben a böngészőben."

# Generic UI strings

ok = "OK"
cancel = "Mégse"
others = "egyéb"
cookie_notice = "A cookie-kat csak a felhasználói beállítások tárolására használjuk. Ha nem szeretné használni őket, ne módosítson semmit ezen az oldalon."
