# Metadata

language_name = "Italiano"
translated_by = "Traduzione: AI"
author = "Creato da Kierownik223"

# Header

home = "Home"
settings = "Impostazioni"
log_in = "Accedi"
manage_account = "Gestisci account"
admin = "Pannello amministratore"
log_out = "Esci"

# Settings

sync_settings = "Sincronizza impostazioni"
sync_success = "Impostazioni salvate con successo."
fetch_settings = "Recupera impostazioni"
fetch_success = "Impostazioni recuperate con successo!"
language = "Lingua"
theme = "Tema"
change_lang = "Cambia lingua (NUOVO!)"
change_theme = "Cambia tema"
theme_default = "Tema predefinito"
theme_darkblu = "Tema blu scuro"
theme_greenish = "Tema verdastro"
theme_antique = "Tema antico (originale)"
plain = "HTML semplice"
enable = "Abilita"
disable = "Disabilita"
hires = "Icone ad alta risoluzione"
smallhead = "Logo con intestazione piccola"
dont_override_settings = "Non sovrascrivere impostazioni"
save_settings = "Salva impostazioni"
reset_settings = "Reimposta impostazioni"

# Files

readme = "Informazioni"
download = "Scarica"
file = "File"
folder = "Cartella"
archive = "Archivio"
zipviewer_title = "Visualizzatore ZIP"
zip_file = "File ZIP"
mdreader_title = "Visualizzatore MD"
reading_markdown = "Lettura file"
file_details = "Dettagli file"
file_name = "Nome file"
file_size = "Dimensione file"
file_downloads = "Download"
print = "Stampa"
viewing_zip = "Visualizzando file ZIP"
watching = "Visualizzando file"

# Uploader

uploader = "Uploader"
upload = "Carica"
select_file = "Seleziona un file"
upload_success = "caricato con successo!"
upload_error = "Si è verificato un errore durante il caricamento del file."
uploader_title = "Uploader file"
target_dir = "Directory di destinazione"
target_placeholder = "Lascia vuoto per /uploads/"
max_size = "Dimensione massima consentita è 100 MB."
select_folder = "Seleziona una cartella"
browse = "Sfoglia"
select_files = "Seleziona file da caricare."
uploading = "Caricamento in corso"

# Account

username = "Nome utente"
password = "Password"
invalid_info = "Nome utente o password non validi."
log_in_with_marmak = "Accedi con un account MARMAK™"
welcome = "Ciao"
tip = "Suggerimento"
settings_tip1 = "Se vuoi mantenere le impostazioni attuali, vai su"
settings_tip2 = "e abilita \"Non sovrascrivere le impostazioni\"."

# Admin

usage = "Utilizzo"
disk_usage = "Utilizzo disco"
sysinfo = "Informazioni server"
memory_usage = "Utilizzo memoria"
system = "Sistema"
kernel_version = "Versione kernel"
hostname = "Nome host"

# Audio player

listening = "Ascoltando file"
album = "Album"
year = "Anno"
genre = "Genere"
album_cover = "Copertina"

# File deletion

delete_success = "rimosso con successo!"
delete_confirmation = "Sei sicuro di voler eliminare"
delete = "Elimina"

# Errors

error = "Errore"
not_found = "Non trovato"
error_400 = "La richiesta inviata non è valida. Riprova."
error_404 = "La risorsa richiesta non è stata trovata. Controlla l'URL e riprova."
error_50x = "Si è verificato un errore interno sul server. Segnalalo."
error_403 = "Attualmente non hai accesso a questa risorsa. Accedi con privilegi più elevati."
no_details = "Nessun dettaglio disponibile!"
no_video = "Il tuo browser non supporta l'elemento video."
no_audio = "Il tuo browser non supporta l'elemento audio."
upload_parse_error = "caricato, ma la risposta non può essere analizzata."
upload_failed_status = "fallito con stato"
upload_failed_network = "caricamento fallito a causa di errore di rete."
error_occured = "Si è verificato un errore:"
error_deleting = "Si è verificato un errore durante la cancellazione del file."
directory_not_empty = "Questa directory non è vuota!"

# Generic UI strings

ok = "OK"
cancel = "Annulla"
others = "altri"
cookie_notice = "Utilizziamo i cookie solo per memorizzare le preferenze dell'utente. Se non desideri utilizzarli, non modificare nulla in questa pagina."
