home = "ホーム"
translated_by = "翻訳: コンピューター"
author = "作成者: Kierownik223"
readme = "情報"
download = "ダウンロード"
zipviewer_title = "ZIPビューア"
mdreader_title = "MDリーダー"
zip_file = "ZIPファイル"
archive = "アーカイブ"
reading_markdown = "ファイルを読み込み中"
not_found = "見つかりません"
file_details = "ファイルの詳細"
file_name = "ファイル名"
file_size = "ファイルサイズ"
file_downloads = "ダウンロード数"
error = "エラー"
language = "言語"
theme = "テーマ"
change_lang = "言語を変更（NEW!）"
change_theme = "テーマを変更"
theme_default = "デフォルトテーマ"
theme_darkblu = "ダークブルーテーマ"
theme_greenish = "グリーン系テーマ"
theme_antique = "アンティーク（オリジナル）テーマ"
plain = "プレーンHTML"
normal_mode = "通常モード"
file = "ファイル"
folder = "ファイルフォルダ"
uploader = "アップローダー"
upload = "アップロード"
select_file = "ファイルを選択"
upload_success = "正常にアップロードされました！"
upload_error = "ファイルのアップロード中にエラーが発生しました。"
uploader_title = "ファイルアップローダー"
admin = "管理パネル"
username = "ユーザー名"
password = "パスワード"
log_in = "ログイン"
log_out = "ログアウト"
invalid_info = "無効なユーザー名またはパスワードです。"
log_in_with_marmak = "MARMAKアカウントでログイン&trade;"
welcome = "こんにちは"
sync_settings = "設定を同期"
sync_success = "設定が正常に保存されました。"
dont_override_settings = "設定を上書きしない"
settings = "設定"
save_settings = "設定を保存"
hires = "高解像度アイコン"
smallhead = "小さいヘッダーロゴ"
enable = "有効化"
disable = "無効化"
target_dir = "ターゲットディレクトリ"
target_placeholder = "/uploads/ を指定しない場合は空のままにしてください。"
fetch_settings = "設定を取得"
fetch_success = "設定が正常に取得されました！"
print = "印刷"
error_400 = "クライアントが無効なリクエストを送信しました。もう一度お試しください。"
error_404 = "要求されたリソースが見つかりませんでした。URLを確認して、再度お試しください。"
error_50x = "内部サーバーエラーが発生しました。報告をお願いします。"
max_size = "最大ファイルサイズは100MBです。"
usage = "使用量"
disk_usage = "ディスク使用量"
sysinfo = "サーバー情報"
manage_account = "アカウント管理"
tip = "ヒント"
settings_tip1 = "現在の設定を保持したい場合は、"
settings_tip2 = "で「設定を上書きしない」を有効にしてください。"
memory_usage = "メモリ使用量"
system = "システム"
kernel_version = "カーネルバージョン"
hostname = "ホスト名"
browse = "参照"
select_folder = "フォルダを選択"
ok = "OK"
cancel = "キャンセル"
viewing_zip = "ZIPファイルを閲覧中"
no_details = "詳細情報なし！"
watching = "ファイルを視聴中"
no_video = "お使いのブラウザはビデオ要素をサポートしていません。"
others = "その他"
select_files = "アップロードするファイルを選択してください。"
uploading = "アップロード中"
upload_parse_error = "アップロードされましたが、応答を解析できませんでした。"
upload_failed_status = "ステータスで失敗しました"
upload_failed_network = "ネットワークエラーによりアップロードに失敗しました。"
no_audio = "お使いのブラウザはオーディオ要素をサポートしていません。"
album = "アルバム"
year = "年"
genre = "ジャンル"
album_cover = "アルバムカバー"
