# Metadata

language_name = "Bahasa Melayu"
translated_by = "Terjemahan: AI"
author = "Dibuat oleh Kierownik223"

# Header

home = "Laman Utama"
settings = "Tetapan"
log_in = "Log masuk"
manage_account = "Urus akaun"
admin = "Panel pentadbir"
log_out = "Log keluar"

# Settings

sync_settings = "Segerak tetapan"
sync_success = "Tetapan berjaya disimpan."
fetch_settings = "Dapatkan tetapan"
fetch_success = "Tetapan berjaya diperoleh!"
language = "Bahasa"
theme = "Tema"
change_lang = "Tukar bahasa (BARU!)"
change_theme = "Tukar tema"
theme_default = "Tema lalai"
theme_darkblu = "Tema biru gelap"
theme_greenish = "Tema kehijauan"
theme_antique = "Tema antik (asal)"
plain = "HTML biasa"
enable = "Aktifkan"
disable = "Lumpuhkan"
hires = "Ikon resolusi tinggi"
smallhead = "Logo kepala kecil"
dont_override_settings = "Jangan timpa tetapan"
save_settings = "Simpan tetapan"
reset_settings = "Tetapkan semula tetapan"
viewers = "Pemapar butiran fail"

# Files

readme = "Maklumat"
download = "Muat turun"
file = "Fail"
folder = "Folder"
archive = "Arkib"
zipviewer_title = "Penonton ZIP"
zip_file = "Fail ZIP"
mdreader_title = "Pembaca MD"
reading_markdown = "Membaca fail"
file_details = "Perincian fail"
file_name = "Nama fail"
file_size = "Saiz fail"
file_downloads = "Muat turun"
print = "Cetak"
viewing_zip = "Melihat fail ZIP"
watching = "Menonton fail"

# Uploader

uploader = "Pengupload"
upload = "Muat naik"
select_file = "Pilih fail"
upload_success = "Berjaya dimuat naik!"
upload_error = "Ralat berlaku semasa memuat naik fail."
uploader_title = "Pengupload Fail"
target_dir = "Direktori sasaran"
target_placeholder = "Kosongkan untuk /uploads/"
max_size = "Saiz fail maksimum dibenarkan ialah 100MB."
select_folder = "Pilih folder"
browse = "Semak imbas"
select_files = "Pilih fail untuk dimuat naik."
uploading = "Sedang memuat naik"

# Account

username = "Nama pengguna"
password = "Kata laluan"
invalid_info = "Nama pengguna atau kata laluan tidak sah."
log_in_with_marmak = "Log masuk dengan Akaun MARMAK™"
welcome = "Hai"
tip = "Petua"
settings_tip1 = "Jika anda mahu mengekalkan tetapan semasa, pergi ke"
settings_tip2 = "dan aktifkan \"Jangan timpa tetapan\"."

# Admin

usage = "Penggunaan"
disk_usage = "Penggunaan cakera"
sysinfo = "Maklumat pelayan"
memory_usage = "Penggunaan memori"
system = "Sistem"
kernel_version = "Versi kernel"
hostname = "Nama hos"

# Audio player

listening = "Mendengar fail"
album = "Album"
year = "Tahun"
genre = "Genre"
album_cover = "Sampul album"

# File deletion

delete_success = "Berjaya dikeluarkan!"
delete_confirmation = "Adakah anda pasti mahu memadamkan ini?"
delete = "Padam"

# Errors

error = "Ralat"
not_found = "Tidak ditemui"
error_400 = "Pelanggan menghantar permintaan yang tidak sah. Sila cuba lagi."
error_404 = "Sumber yang diminta tidak dapat dijumpai. Sila semak URL dan cuba lagi."
error_50x = "Ralat pelayan dalaman telah berlaku. Sila laporkan kepada kami."
error_403 = "Anda tidak mempunyai akses ke sumber ini. Sila log masuk sebagai pengguna yang lebih berkuasa."
no_details = "Tiada butiran tersedia!"
no_video = "Pelayar anda tidak menyokong elemen video."
no_audio = "Pelayar anda tidak menyokong elemen audio."
upload_parse_error = "Telah dimuat naik, tetapi tindak balas tidak dapat diurai."
upload_failed_status = "gagal dengan status"
upload_failed_network = "muat naik gagal kerana ralat rangkaian."
error_occured = "Ralat berlaku:"
error_deleting = "Ralat berlaku semasa memadam fail."
directory_not_empty = "Direktori ini tidak kosong!"
upload_not_supported = "Pemuat naik JavaScript tidak disokong oleh pelayar ini."

# Generic UI strings

ok = "OK"
cancel = "Batal"
others = "lain-lain"
cookie_notice = "Kami hanya menggunakan kuki untuk menyimpan keutamaan pengguna. Jika anda tidak mahu menggunakannya, jangan ubah apa-apa di halaman ini."
