# Metadata

language_name = "Norsk"
translated_by = "Oversettelse: AI"
author = "Laget av Kierownik223"

# Header

home = "Hjem"
settings = "Innstillinger"
log_in = "Logg inn"
manage_account = "Administrer konto"
admin = "Adminpanel"
log_out = "Logg ut"

# Settings

sync_settings = "Synkroniser innstillinger"
sync_success = "Innstillinger lagret."
fetch_settings = "Hent innstillinger"
fetch_success = "Innstillinger hentet!"
language = "Språk"
theme = "Tema"
change_lang = "Bytt språk (NYTT!)"
change_theme = "Bytt tema"
theme_default = "Standardtema"
theme_darkblu = "Mørkeblått tema"
theme_greenish = "Grønnlig tema"
theme_antique = "Antikk (original) tema"
plain = "Ren HTML"
enable = "Aktiver"
disable = "Deaktiver"
hires = "Ikoner i høy oppløsning"
smallhead = "Lite header-logo"
dont_override_settings = "Ikke overstyr innstillinger"
save_settings = "Lagre innstillinger"
reset_settings = "Tilbakestill innstillinger"

# Files

readme = "Informasjon"
download = "Last ned"
file = "Fil"
folder = "Mappe"
archive = "Arkiv"
zipviewer_title = "ZIP-visning"
zip_file = "ZIP-fil"
mdreader_title = "MD-leser"
reading_markdown = "Laster fil"
file_details = "Filinformasjon"
file_name = "Filnavn"
file_size = "Filstørrelse"
file_downloads = "Nedlastinger"
print = "Skriv ut"
viewing_zip = "Viser ZIP-fil"
watching = "Ser på fil"

# Uploader

uploader = "Opplaster"
upload = "Last opp"
select_file = "Velg fil"
upload_success = "lastet opp!"
upload_error = "En feil oppstod under opplasting."
uploader_title = "Filopplaster"
target_dir = "Målmappe"
target_placeholder = "La stå tomt for /uploads/"
max_size = "Maks filstørrelse er 100MB."
select_folder = "Velg mappe"
browse = "Bla gjennom"
select_files = "Velg filer for opplasting."
uploading = "Laster opp"

# Account

username = "Brukernavn"
password = "Passord"
invalid_info = "Ugyldig brukernavn eller passord."
log_in_with_marmak = "Logg inn med MARMAK-konto™"
welcome = "Hei"
tip = "Tips"
settings_tip1 = "Hvis du vil beholde innstillingene dine, gå til"
settings_tip2 = "og aktiver \"Ikke overstyr innstillinger\"."

# Admin

usage = "Bruk"
disk_usage = "Diskbruk"
sysinfo = "Serverinformasjon"
memory_usage = "Minnebruk"
system = "System"
kernel_version = "Kjernerversjon"
hostname = "Vertsnavn"

# Audio player

listening = "Lytter til fil"
album = "Album"
year = "År"
genre = "Sjanger"
album_cover = "Albumomslag"

# File deletion

delete_success = "fjernet!"
delete_confirmation = "Er du sikker på at du vil slette dette?"
delete = "Slett"

# Errors

error = "Feil"
not_found = "Ikke funnet"
error_400 = "Klienten sendte en ugyldig forespørsel. Prøv igjen."
error_404 = "Ressursen ble ikke funnet. Sjekk URL og prøv igjen."
error_50x = "En intern serverfeil har oppstått. Vennligst rapporter dette."
error_403 = "Du har ikke tilgang til denne ressursen. Vennligst logg inn med høyere privilegier."
no_details = "Ingen detaljer tilgjengelig!"
no_video = "Nettleseren din støtter ikke videoelementet."
no_audio = "Nettleseren din støtter ikke audioelementet."
upload_parse_error = "lastet opp, men svaret kunne ikke tolkes."
upload_failed_status = "feilet med status"
upload_failed_network = "opplasting feilet på grunn av nettverksfeil."
error_occured = "En feil oppstod:"
error_deleting = "En feil oppstod under sletting av fil."
directory_not_empty = "Denne katalogen er ikke tom!"

# Generic UI strings

ok = "OK"
cancel = "Avbryt"
others = "andre"
cookie_notice = "Vi bruker kun informasjonskapsler for å lagre brukerinnstillinger. Hvis du ikke ønsker å bruke dem, ikke endre noe på denne siden."
