home = "Start"
translated_by = "Tłumaczenie: Kierownik223"
author = "Stworzone przez Kierownik223"
readme = "Informacje"
download = "Pobierz"
zipviewer_title = "Przeglądarka ZIP"
mdreader_title = "Czytnik MD"
zip_file = "Plik ZIP"
archive = "Archiwum"
reading_markdown = "Czytanie pliku"
not_found = "Nie znaleziono"
file_details = "Szczegóły pliku"
file_name = "Nazwa"
file_size = "Rozmiar"
file_downloads = "Pobrania"
error = "Błąd"
language = "Język"
theme = "Motyw"
change_lang = "Zmień język (NOWOŚĆ!)"
change_theme = "Zmień motyw"
theme_default = "Motyw domyślny"
theme_darkblu = "Motyw ciemnoniebieski"
theme_greenish = "Motwy zielonkawy"
theme_antique = "Motyw antyczny (orginalny)"
plain = "Czysty HTML"
normal_mode = "Tryb normalny"
file = "plik"
folder = "Katalog"
uploader = "Wrzucarka"
upload = "Wrzuć"
select_file = "Wybierz plik"
upload_success = "został wrzucony pomyślnie!"
upload_error = "Wystąpił błąd podczas wrzucania pliku."
uploader_title = "Wrzucarka plików"
admin = "Administracja"
username = "Nazwa użytkownika"
password = "Hasło"
log_in = "Zaloguj się"
log_out = "Wyloguj się"
invalid_info = "Niepoprawna nazwa użytkownika lub hasło"
log_in_with_marmak = "Zaloguj się z Kontem MARMAK&trade;"
welcome = "Witaj"
sync_settings = "Synchronizuj ustawienia"
sync_success = "Ustawienia zostały zapisane."
dont_override_settings = "Nie nadpisuj ustawień"
settings = "Ustawienia"
save_settings = "Zapisz ustawienia"
hires = "Ikony w wysokiej rozdzielczości"
smallhead = "Małe logo"
enable = "Włącz"
disable = "Wyłącz"
target_dir = "Katalog docelowy"
target_placeholder = "Zostaw puste dla /uploads/"
fetch_settings = "Pobierz ustawienia"
fetch_success = "Ustawienia pobrane pomyślnie!"
print = "Drukuj"
error_400 = "Klient wysłał niepoprawne zapytanie. Spróbuj ponownie,"
error_404 = "Nie ma takiego pliku. Sprawdź URL i spróbuj ponownie."
error_50x = "Wystąpił wewnętrzny błąd serwera. Skontakuj się z nami, aby go zgłosić."
error_403 = "Nie masz uprawnień do tego zasobu. Zaloguj się jako wyżej uprawniony użytkownik i spróbuj ponownie."
max_size = "Maksymalny rozmiar pliku to 100 MB."
usage = "Zużycie"
disk_usage = "Użycie dysku"
sysinfo = "Inf. o serwerze"
manage_account = "Zarządzaj kontem"
tip = "Wskazówka"
settings_tip1 = "Jeżeli chcesz zachować swoje aktualne ustawienia, przejdź do"
settings_tip2 = "i włącz \"Nie nadpisuj ustawień\"."
memory_usage = "Użycie RAM"
system = "System"
kernel_version = "Wersja kernela"
hostname = "Nazwa hosta"
browse = "Przeglądaj"
select_folder = "Wybierz folder"
ok = "OK"
cancel = "Anuluj"
viewing_zip = "Przeglądanie ZIP"
no_details = "Brak detali!"
watching = "Oglądanie pliku"
no_video = "Twoja przeglądarka nie wspiera elementu video."
others = "innych"
select_files = "Wybierz pliki do wrzucenia."
uploading = "Wrzucanie"
upload_parse_error = "został wrzucony, ale odpowiedź nie mogła być odczytana."
upload_failed_status = "nie powiódł się - HTTP"
upload_failed_network = "nie powiódł się - Błąd sieci."
listening = "Słuchanie pliku"
no_audio = "Twoja przeglądarka nie wspiera elementu audio."
album = "Album"
year = "Rok"
genre = "Gatunek"
album_cover = "Okładka albumu"
