# Metadata

language_name = "Polski"
translated_by = "Tłumaczenie: Kierownik223"
author = "Stworzone przez Kierownik223"

# Header

home = "Start"
settings = "Ustawienia"
log_in = "Zaloguj się"
manage_account = "Zarządzaj kontem"
admin = "Administracja"
log_out = "Wyloguj się"

# Settings

sync_settings = "Synchronizuj ustawienia"
sync_success = "Ustawienia zsynchronizowane pomyślnie."
fetch_settings = "Pobierz ustawienia"
fetch_success = "Ustawienia pobrane pomyślnie."
language = "Język"
theme = "Motyw"
change_lang = "Zmień język (NOWOŚĆ!)"
change_theme = "Zmień motyw"
theme_default = "Domyślny"
theme_darkblue = "Ciemnoniebieski"
theme_greenish = "Zielonkawy"
theme_antique = "Antyczny (oryginalny)"
plain = "Czysty HTML"
enable = "Włącz"
disable = "Wyłącz"
hires = "Ikony w wysokiej rozdzielczości"
smallhead = "Małe logo w nagłówku"
dont_override_settings = "Nie nadpisuj ustawień"
save_settings = "Zapisz ustawienia"
reset_settings = "Resetuj ustawienia"
viewers = "Przeglądarki szczegółów plików"

# Files

readme = "Informacje"
download = "Pobierz"
file = "Plik"
folder = "Katalog"
archive = "Archiwum"
zipviewer_title = "Przeglądarka ZIP"
zip_file = "Plik ZIP"
mdreader_title = "Czytnik MD"
reading_markdown = "Czytanie pliku"
file_details = "Szczegóły pliku"
file_name = "Nazwa"
file_size = "Rozmiar"
file_downloads = "Pobrania"
print = "Drukuj"
viewing_zip = "Przeglądarka pliku ZIP"
watching = "Oglądanie pliku"
download_zip = "Pobierz ZIP"
preparing_zip = "Przygotowywanie ZIP..."
rename = "Zmień nazwę"
rename_success = "Nazwa zmieniona pomyślnie!"
new_name = "Nowa nazwa"
error_renaming = "Podczas zmieniania nazwy wystąpił błąd"

# Uploader

uploader = "Wrzucarka"
upload = "Wrzuć"
select_file = "Wybierz plik"
upload_success = "wrzucony pomyślnie!"
upload_error = "Podczas wrzucania pliku wystąpił błąd."
uploader_title = "Wrzucarka plików"
target_dir = "Katalog docelowy"
target_placeholder = "Pozostaw pusty, aby użyć /uploads/"
max_size = "Maksymalny rozmiar pliku wynosi 100MB."
select_folder = "Wybierz katalog"
browse = "Przeglądaj"
select_files = "Wybierz pliki"
uploading = "Wrzucanie"

# Account

username = "Nazwa użytkownika"
password = "Hasło"
invalid_info = "Nieprawidłowa nazwa użytkownika lub hasło."
log_in_with_marmak = "Zaloguj się z kontem MARMAK&trade;"
welcome = "Witaj"
tip = "Wskazówka"
settings_tip1 = "Jeżeli chcesz zachować swoje aktualne ustawienia, przejdź do"
settings_tip2 = "i włącz \"Nie nadpisuj ustawień\"."
login_to_continue = "Zaloguj się, aby przejść do"

# Admin

usage = "Użycie"
disk_usage = "Użycie dysku"
sysinfo = "Informacje o serwerze"
memory_usage = "Użycie pamięci"
system = "System"
kernel_version = "Wersja jądra"
hostname = "Nazwa hosta"

# Audio player

listening = "Słuchanie pliku"
album = "Album"
year = "Rok"
genre = "Gatunek"
album_cover = "Okładka albumu"

# File deletion

delete_success = "usunięty pomyślnie!"
delete_confirmation = "Czy na pewno chcesz usunąć"
delete = "Usuń"

# Errors

error = "Błąd"
not_found = "Nie znaleziono"
error_400 = "Klient wysłał niepoprawne zapytanie. Spróbuj ponownie,"
error_404 = "Nie ma takiego pliku. Sprawdź URL i spróbuj ponownie."
error_50x = "Wystąpił wewnętrzny błąd serwera. Skontakuj się z nami, aby go zgłosić."
error_403 = "Nie masz uprawnień do tego zasobu. Zaloguj się jako wyżej uprawniony użytkownik i spróbuj ponownie."
no_details = "Brak detali!"
no_video = "Twoja przeglądarka nie wspiera elementu video."
no_audio = "Twoja przeglądarka nie wspiera elementu audio."
upload_parse_error = "wrzucony, ale odpowiedź nie została przetworzona."
upload_failed_status = "nie wrzucony, HTTP"
upload_failed_network = "nie wrzucony, ponieważ wystąpił błąd sieci."
error_occured = "Wystąpił błąd:"
error_deleting = "Podczas usuwania pliku wystąpił błąd."
directory_not_empty = "Ten katalog nie jest pusty!"
upload_not_supported = "Wrzucarka JavaScript nie jest wspierana przez tę przeglądarkę."
private_folder = "Zaloguj się, aby uzyskać dostęp do prywatnego folderu!"

# Generic UI strings

ok = "OK"
cancel = "Anuluj"
others = "innych"
cookie_notice = "Używamy ciasteczek (cookies) tylko i wyłącznie do przechowywania ustawień użytkownika. Jeśli nie chcesz ich używać, nie zmieniaj niczego na tej stronie."
