# Metadata

language_name = "Română"
translated_by = "Translation: AI"
author = "Made by Kierownik223"

# Header

home = "Pagina principală"
settings = "Setări"
log_in = "Autentificare"
manage_account = "Gestionare cont"
admin = "Panou de administrare"
log_out = "Deconectare"

# Settings

sync_settings = "Sincronizare setări"
sync_success = "Setările au fost salvate cu succes."
fetch_settings = "Preluare setări"
fetch_success = "Setările au fost preluate cu succes!"
language = "Limba"
theme = "Temă"
change_lang = "Schimbă limba (NOU!)"
change_theme = "Schimbă tema"
theme_default = "Temă implicită"
theme_darkblu = "Temă albastru închis"
theme_greenish = "Temă verzulie"
theme_antique = "Temă antică (originală)"
plain = "HTML simplu"
enable = "Activează"
disable = "Dezactivează"
hires = "Icoane de înaltă rezoluție"
smallhead = "Logo mic antet"
dont_override_settings = "Nu suprascrie setările"
save_settings = "Salvează setările"
reset_settings = "Resetează setările"

# Files

readme = "Informații"
download = "Descarcă"
file = "Fișier"
folder = "Director de fișiere"
archive = "Arhivă"
zipviewer_title = "Vizualizator ZIP"
zip_file = "Fișier ZIP"
mdreader_title = "Cititor MD"
reading_markdown = "Citire fișier"
file_details = "Detalii fișier"
file_name = "Nume fișier"
file_size = "Dimensiune fișier"
file_downloads = "Descărcări"
print = "Printează"
viewing_zip = "Vizualizare fișier ZIP"
watching = "Vizualizare fișier"

# Uploader

uploader = "Încărcător"
upload = "Încarcă"
select_file = "Selectează un fișier"
upload_success = "încărcat cu succes!"
upload_error = "A apărut o eroare la încărcarea fișierului."
uploader_title = "Încărcător de fișiere"
target_dir = "Director țintă"
target_placeholder = "Lasă gol pentru /uploads/"
max_size = "Dimensiunea maximă permisă a fișierului este de 100MB."
select_folder = "Selectează un director"
browse = "Navighează"
select_files = "Selectează fișierele de încărcat."
uploading = "Se încarcă"

# Account

username = "Nume utilizator"
password = "Parolă"
invalid_info = "Nume de utilizator sau parolă invalidă."
log_in_with_marmak = "Autentificare cu un cont MARMAK&trade;"
welcome = "Salut"
tip = "Sfat"
settings_tip1 = "Dacă doriți să păstrați setările curente, accesați"
settings_tip2 = "și activați „Nu suprascrie setările”."

# Admin

usage = "Utilizare"
disk_usage = "Utilizare disc"
sysinfo = "Informații server"
memory_usage = "Utilizare memorie"
system = "Sistem"
kernel_version = "Versiune kernel"
hostname = "Nume gazdă"

# Audio player

listening = "Se ascultă fișierul"
album = "Album"
year = "An"
genre = "Gen"
album_cover = "Coperta albumului"

# File deletion

delete_success = "eliminat cu succes!"
delete_confirmation = "Ești sigur că vrei să ștergi"
delete = "Șterge"

# Errors

error = "Eroare"
not_found = "Nu a fost găsit"
error_400 = "Clientul a trimis o cerere invalidă. Vă rugăm să încercați din nou."
error_404 = "Resursa solicitată nu a putut fi localizată. Vă rugăm să verificați URL-ul și să încercați din nou."
error_50x = "A apărut o eroare internă a serverului. Vă rugăm să ne raportați acest lucru."
error_403 = "Momentan nu aveți acces la această resursă. Vă rugăm să vă autentificați ca un utilizator cu privilegii mai mari."
no_details = "Nu sunt disponibile detalii!"
no_video = "Browserul dumneavoastră nu acceptă elementul video."
no_audio = "Browserul dumneavoastră nu acceptă elementul audio."
upload_parse_error = "încărcat, dar răspunsul nu a putut fi parsificat."
upload_failed_status = "eșuat cu starea"
upload_failed_network = "încărcarea a eșuat din cauza unei erori de rețea."
error_occured = "A apărut o eroare:"
error_deleting = "A apărut o eroare la ștergerea fișierului."
directory_not_empty = "Acest director nu este gol!"

# Generic UI strings

ok = "OK"
cancel = "Anulează"
others = "alții"
cookie_notice = "Folosim cookie-uri doar pentru a stoca preferințele utilizatorului. Dacă nu doriți să le utilizați, nu schimbați nimic pe această pagină."
