# Metadata

language_name = "Slovenščina"
translated_by = "Prevod: AI"
author = "Ustvaril: Kierownik223"

# Header

home = "Domača stran"
settings = "Nastavitve"
log_in = "Prijava"
manage_account = "Upravljanje računa"
admin = "Administratorska plošča"
log_out = "Odjava"

# Settings

sync_settings = "Sinhroniziraj nastavitve"
sync_success = "Nastavitve uspešno shranjene."
fetch_settings = "Pridobi nastavitve"
fetch_success = "Nastavitve uspešno pridobljene!"
language = "Jezik"
theme = "Tema"
change_lang = "Spremeni jezik (NOVO!)"
change_theme = "Spremeni temo"
theme_default = "Privzeta tema"
theme_darkblu = "Temno modra tema"
theme_greenish = "Zelenkasta tema"
theme_antique = "Antična (izvirna) tema"
plain = "Goli HTML"
enable = "Omogoči"
disable = "Onemogoči"
hires = "Ikone visoke ločljivosti"
smallhead = "Majhen logotip v glavi"
dont_override_settings = "Ne prepiši nastavitev"
save_settings = "Shrani nastavitve"
reset_settings = "Ponastavi nastavitve"

# Files

readme = "Informacije"
download = "Prenesi"
file = "Datoteka"
folder = "Mapa datotek"
archive = "Arhiv"
zipviewer_title = "ZIP pregledovalnik"
zip_file = "ZIP datoteka"
mdreader_title = "MD bralnik"
reading_markdown = "Branje datoteke"
file_details = "Podrobnosti datoteke"
file_name = "Ime datoteke"
file_size = "Velikost datoteke"
file_downloads = "Prenosi"
print = "Natisni"
viewing_zip = "Ogled ZIP datoteke"
watching = "Ogled datoteke"

# Uploader

uploader = "Nalaganje"
upload = "Naloži"
select_file = "Izberi datoteko"
upload_success = "uspešno naloženo!"
upload_error = "Prišlo je do napake pri nalaganju datoteke."
uploader_title = "Nalaganje datotek"
target_dir = "Ciljna mapa"
target_placeholder = "Pustite prazno za /uploads/"
max_size = "Največja dovoljena velikost datoteke je 100 MB."
select_folder = "Izberi mapo"
browse = "Brskaj"
select_files = "Izberite datoteke za nalaganje."
uploading = "Nalaganje"

# Account

username = "Uporabniško ime"
password = "Geslo"
invalid_info = "Neveljavno uporabniško ime ali geslo."
log_in_with_marmak = "Prijava z MARMAK računom&trade;"
welcome = "Pozdravljeni"
tip = "Namig"
settings_tip1 = "Če želite ohraniti trenutne nastavitve, pojdite na"
settings_tip2 = "in omogočite \"Ne prepiši nastavitev\"."

# Admin

usage = "Poraba"
disk_usage = "Poraba diska"
sysinfo = "Informacije o strežniku"
memory_usage = "Poraba pomnilnika"
system = "Sistem"
kernel_version = "Različica jedra"
hostname = "Ime gostitelja"

# Audio player

listening = "Poslušanje datoteke"
album = "Album"
year = "Leto"
genre = "Žanr"
album_cover = "Naslovnica albuma"

# File deletion

delete_success = "uspešno izbrisano!"
delete_confirmation = "Ali ste prepričani, da želite izbrisati"
delete = "Izbriši"

# Errors

error = "Napaka"
not_found = "Ni najdeno"
error_400 = "Odjemalec je poslal neveljavno zahtevo. Poskusite znova."
error_404 = "Zahtevani vir ni bil najden. Preverite URL in poskusite znova."
error_50x = "Prišlo je do notranje napake strežnika. Prosimo, prijavite nam težavo."
error_403 = "Trenutno nimate dostopa do tega vira. Prijavite se kot uporabnik z višjimi privilegiji."
no_details = "Podrobnosti niso na voljo!"
no_video = "Vaš brskalnik ne podpira video elementa."
no_audio = "Vaš brskalnik ne podpira audio elementa."
upload_parse_error = "naloženo, vendar odziva ni bilo mogoče razčleniti."
upload_failed_status = "ni uspelo s statusom"
upload_failed_network = "nalaganje ni uspelo zaradi napake omrežja."
error_occured = "Prišlo je do napake:"
error_deleting = "Napaka pri brisanju datoteke."
directory_not_empty = "Mapa ni prazna!"
upload_not_supported = "Ta brskalnik ne podpira JavaScript nalaganja."

# Generic UI strings

ok = "V redu"
cancel = "Prekliči"
others = "drugi"
cookie_notice = "Piškotke uporabljamo samo za shranjevanje uporabniških nastavitev. Če jih ne želite uporabljati, na tej strani ničesar ne spreminjajte."
