# Metadata

language_name = "Svenska"
translated_by = "Översättning: AI"
author = "Skapad av Kierownik223"

# Header

home = "Hem"
settings = "Inställningar"
log_in = "Logga in"
manage_account = "Hantera konto"
admin = "Adminpanel"
log_out = "Logga ut"

# Settings

sync_settings = "Synkronisera inställningar"
sync_success = "Inställningarna sparades."
fetch_settings = "Hämta inställningar"
fetch_success = "Inställningar hämtade!"
language = "Språk"
theme = "Tema"
change_lang = "Byt språk (NYTT!)"
change_theme = "Byt tema"
theme_default = "Standardtema"
theme_darkblu = "Mörkblått tema"
theme_greenish = "Grönaktigt tema"
theme_antique = "Antikt (original) tema"
plain = "Ren HTML"
enable = "Aktivera"
disable = "Inaktivera"
hires = "Ikoner med hög upplösning"
smallhead = "Liten header-logga"
dont_override_settings = "Skriv inte över inställningar"
save_settings = "Spara inställningar"
reset_settings = "Återställ inställningar"
viewers = "Filinformationsvisare"

# Files

readme = "Information"
download = "Ladda ner"
file = "Fil"
folder = "Mapp"
archive = "Arkiv"
zipviewer_title = "ZIP-visare"
zip_file = "ZIP-fil"
mdreader_title = "MD-läsare"
reading_markdown = "Läser fil"
file_details = "Filinformation"
file_name = "Filnamn"
file_size = "Filstorlek"
file_downloads = "Nedladdningar"
print = "Skriv ut"
viewing_zip = "Visar ZIP-fil"
watching = "Visar fil"

# Uploader

uploader = "Uppladdare"
upload = "Ladda upp"
select_file = "Välj fil"
upload_success = "uppladdad!"
upload_error = "Ett fel inträffade vid uppladdning."
uploader_title = "Filuppladdare"
target_dir = "Målmapp"
target_placeholder = "Lämna tomt för /uploads/"
max_size = "Maximal filstorlek är 100MB."
select_folder = "Välj mapp"
browse = "Bläddra"
select_files = "Välj filer att ladda upp."
uploading = "Laddar upp"

# Account

username = "Användarnamn"
password = "Lösenord"
invalid_info = "Ogiltigt användarnamn eller lösenord."
log_in_with_marmak = "Logga in med MARMAK-konto™"
welcome = "Hej"
tip = "Tips"
settings_tip1 = "Om du vill behålla dina inställningar, gå till"
settings_tip2 = "och aktivera \"Skriv inte över inställningar\"."

# Admin

usage = "Användning"
disk_usage = "Diskanvändning"
sysinfo = "Serverinformation"
memory_usage = "Minnesanvändning"
system = "System"
kernel_version = "Kärnversion"
hostname = "Värdnamn"

# Audio player

listening = "Lyssnar på fil"
album = "Album"
year = "År"
genre = "Genre"
album_cover = "Albumomslag"

# File deletion

delete_success = "borttagen!"
delete_confirmation = "Är du säker på att du vill ta bort detta?"
delete = "Ta bort"

# Errors

error = "Fel"
not_found = "Hittades inte"
error_400 = "Klienten skickade en ogiltig förfrågan. Vänligen försök igen."
error_404 = "Den begärda resursen kunde inte hittas. Kontrollera URL och försök igen."
error_50x = "Ett internt serverfel har inträffat. Vänligen rapportera detta."
error_403 = "Du har inte tillgång till denna resurs. Logga in som en användare med högre behörighet."
no_details = "Inga detaljer tillgängliga!"
no_video = "Din webbläsare stöder inte videoelementet."
no_audio = "Din webbläsare stöder inte audioelementet."
upload_parse_error = "uppladdad, men svar kunde inte tolkas."
upload_failed_status = "misslyckades med status"
upload_failed_network = "uppladdning misslyckades på grund av nätverksfel."
error_occured = "Ett fel uppstod:"
error_deleting = "Ett fel uppstod vid borttagning av fil."
directory_not_empty = "Denna katalog är inte tom!"
upload_not_supported = "JavaScript-uppladdning stöds inte av den här webbläsaren."

# Generic UI strings

ok = "OK"
cancel = "Avbryt"
others = "andra"
cookie_notice = "Vi använder cookies endast för att spara användarinställningar. Om du inte vill använda dem, ändra inget på denna sida."
