# Metadata

language_name = "Türkçe"
translated_by = "Çeviri: AI"
author = "Hazırlayan: Kierownik223"

# Header

home = "Ana Sayfa"
settings = "Ayarlar"
log_in = "Giriş Yap"
manage_account = "Hesabı Yönet"
admin = "Yönetici Paneli"
log_out = "Çıkış Yap"

# Settings

sync_settings = "Ayarları Senkronize Et"
sync_success = "Ayarlar başarıyla kaydedildi."
fetch_settings = "Ayarları Getir"
fetch_success = "Ayarlar başarıyla alındı!"
language = "Dil"
theme = "Tema"
change_lang = "Dil Değiştir (YENİ!)"
change_theme = "Tema Değiştir"
theme_default = "Varsayılan Tema"
theme_darkblu = "Koyu Mavi Tema"
theme_greenish = "Yeşilimsi Tema"
theme_antique = "Antik (orijinal) Tema"
plain = "Sade HTML"
enable = "Etkinleştir"
disable = "Devre Dışı Bırak"
hires = "Yüksek çözünürlüklü simgeler"
smallhead = "Küçük başlık logosu"
dont_override_settings = "Ayarları geçersiz kılma"
save_settings = "Ayarları Kaydet"
reset_settings = "Ayarları sıfırla"

# Files

readme = "Bilgi"
download = "İndir"
file = "Dosya"
folder = "Klasör"
archive = "Arşiv"
zipviewer_title = "ZIP Görüntüleyici"
zip_file = "ZIP dosyası"
mdreader_title = "MD Okuyucu"
reading_markdown = "Dosya okunuyor"
file_details = "Dosya Detayları"
file_name = "Dosya Adı"
file_size = "Dosya Boyutu"
file_downloads = "İndirmeler"
print = "Yazdır"
viewing_zip = "ZIP dosyası görüntüleniyor"
watching = "Dosya görüntüleniyor"

# Uploader

uploader = "Yükleyici"
upload = "Yükle"
select_file = "Dosya Seç"
upload_success = "başarıyla yüklendi!"
upload_error = "Yükleme sırasında hata oluştu."
uploader_title = "Dosya Yükleyici"
target_dir = "Hedef Klasör"
target_placeholder = "Boş bırak /uploads/"
max_size = "Maksimum dosya boyutu 100MB."
select_folder = "Klasör Seç"
browse = "Gözat"
select_files = "Yükleme için dosya seç."
uploading = "Yükleniyor"

# Account

username = "Kullanıcı Adı"
password = "Şifre"
invalid_info = "Geçersiz kullanıcı adı veya şifre."
log_in_with_marmak = "MARMAK hesabı ile giriş yap™"
welcome = "Hoşgeldiniz"
tip = "İpucu"
settings_tip1 = "Mevcut ayarları korumak için şuraya gidin"
settings_tip2 = "ve \"Ayarları geçersiz kılma\" seçeneğini açın."

# Admin

usage = "Kullanım"
disk_usage = "Disk Kullanımı"
sysinfo = "Sunucu Bilgisi"
memory_usage = "Bellek Kullanımı"
system = "Sistem"
kernel_version = "Çekirdek Versiyonu"
hostname = "Sunucu Adı"

# Audio player

listening = "Dosya dinleniyor"
album = "Albüm"
year = "Yıl"
genre = "Tür"
album_cover = "Albüm Kapak"

# File deletion

delete_success = "başarıyla silindi!"
delete_confirmation = "Bunu silmek istediğinizden emin misiniz?"
delete = "Sil"

# Errors

error = "Hata"
not_found = "Bulunamadı"
error_400 = "İstemci geçersiz istek gönderdi. Lütfen tekrar deneyin."
error_404 = "İstenen kaynak bulunamadı. URL'yi kontrol edin ve tekrar deneyin."
error_50x = "Sunucuda dahili bir hata oluştu. Lütfen bize bildirin."
error_403 = "Bu kaynağa erişim izniniz yok. Lütfen daha yüksek yetkili kullanıcı olarak giriş yapın."
no_details = "Detay yok!"
no_video = "Tarayıcınız video öğesini desteklemiyor."
no_audio = "Tarayıcınız ses öğesini desteklemiyor."
upload_parse_error = "yüklendi ancak yanıt işlenemedi."
upload_failed_status = "durumuyla başarısız oldu"
upload_failed_network = "ağ hatası nedeniyle yükleme başarısız oldu."
error_occured = "Hata oluştu:"
error_deleting = "Dosya silinirken hata oluştu."
directory_not_empty = "Bu dizin boş değil!"
upload_not_supported = "Bu tarayıcı JavaScript yükleyicisini desteklemiyor."

# Generic UI strings

ok = "Tamam"
cancel = "İptal"
others = "diğerleri"
cookie_notice = "Çerezleri yalnızca kullanıcı tercihlerini saklamak için kullanıyoruz. Bunları kullanmak istemiyorsanız, bu sayfada hiçbir şeyi değiştirmeyin."
