home = "Головна"
translated_by = "Переклад: Kierownik223"
author = "Автор: Kierownik223"
readme = "Інформація"
download = "Завантажити"
zipviewer_title = "Переглядач ZIP"
mdreader_title = "Читач MD"
zip_file = "ZIP-файл"
archive = "Архів"
reading_markdown = "Читання файлу"
not_found = "Не знайдено"
file_details = "Деталі файлу"
file_name = "Назва файлу"
file_size = "Розмір файлу"
file_downloads = "Завантаження"
error = "Помилка"
language = "Мова"
theme = "Тема"
change_lang = "Змінити мову (НОВЕ!)"
change_theme = "Змінити тему"
theme_default = "Стандартна тема"
theme_darkblu = "Темно-синя тема"
theme_greenish = "Зеленувата тема"
theme_antique = "Антична (оригінальна) тема"
plain = "Простий HTML"
normal_mode = "Звичайний режим"
file = "Файл"
folder = "Папка файлів"
uploader = "Завантажувач"
upload = "Завантажити"
select_file = "Вибрати файл"
upload_success = "успішно завантажено!"
upload_error = "Під час завантаження файлу сталася помилка."
uploader_title = "Завантажувач файлів"
admin = "Адміністративна панель"
username = "Ім'я користувача"
password = "Пароль"
log_in = "Увійти"
log_out = "Вийти"
invalid_info = "Невірне ім'я користувача або пароль."
log_in_with_marmak = "Увійти за допомогою MARMAK Account&trade;"
welcome = "Привіт"
sync_settings = "Синхронізувати налаштування"
sync_success = "Налаштування успішно збережено."
dont_override_settings = "Не перезаписувати налаштування"
settings = "Налаштування"
save_settings = "Зберегти налаштування"
hires = "Високоякісні іконки"
smallhead = "Малий логотип у заголовку"
enable = "Увімкнути"
disable = "Вимкнути"
target_dir = "Цільова директорія"
target_placeholder = "Залиште порожнім для /uploads/"
fetch_settings = "Отримати налаштування"
fetch_success = "Налаштування успішно отримано!"
print = "Друк"
error_400 = "Клієнт надіслав некоректний запит. Будь ласка, спробуйте ще раз."
error_404 = "Запитуваний ресурс не знайдено. Будь ласка, перевірте URL і спробуйте ще раз."
error_50x = "Виникла внутрішня помилка сервера. Будь ласка, повідомте нам про це."
max_size = "Максимальний розмір файлу — 100MB."
usage = "Використання"
disk_usage = "Використання диску"
sysinfo = "Інформація про сервер"
manage_account = "Керування акаунтом"
tip = "Порада"
settings_tip1 = "Якщо ви хочете зберегти поточні налаштування, перейдіть до"
settings_tip2 = "і увімкніть \"Не перезаписувати налаштування\"."
memory_usage = "Використання пам'яті"
system = "Система"
kernel_version = "Версія ядра"
hostname = "Ім'я хоста"
browse = "Переглянути"
select_folder = "Вибрати папку"
ok = "OK"
cancel = "Скасувати"
viewing_zip = "Перегляд ZIP-файлу"
no_details = "Немає доступних деталей!"
watching = "Перегляд файлу"
no_video = "Ваш браузер не підтримує відеоелемент."
others = "інші"
select_files = "Виберіть файли для завантаження."
uploading = "Завантаження"
upload_parse_error = "завантажено, але не вдалося обробити відповідь."
upload_failed_status = "не вдалося зі статусом"
upload_failed_network = "не вдалося завантажити через помилку мережі."
