# Metadata

language_name = "Українська"
translated_by = "Переклад: Машинний"
author = "Створено Kierownik223"

# Header

home = "Головна"
settings = "Налаштування"
log_in = "Увійти"
manage_account = "Керування обліковим записом"
admin = "Панель адміністратора"
log_out = "Вийти"

# Settings

sync_settings = "Синхронізувати налаштування"
sync_success = "Налаштування успішно збережено."
fetch_settings = "Отримати налаштування"
fetch_success = "Налаштування успішно отримано!"
language = "Мова"
theme = "Тема"
change_lang = "Змінити мову (НОВЕ!)"
change_theme = "Змінити тему"
theme_default = "Типова тема"
theme_darkblu = "Темно-синя тема"
theme_greenish = "Зеленувата тема"
theme_antique = "Антикварна (оригінальна) тема"
plain = "Простий HTML"
enable = "Увімкнути"
disable = "Вимкнути"
hires = "Іконки високої роздільності"
smallhead = "Маленький логотип у заголовку"
dont_override_settings = "Не перезаписувати налаштування"
save_settings = "Зберегти налаштування"

# Files

readme = "Інформація"
download = "Завантажити"
file = "Файл"
folder = "Тека"
archive = "Архів"
zipviewer_title = "Переглядач ZIP"
zip_file = "ZIP-файл"
mdreader_title = "Читач MD"
reading_markdown = "Читання файлу"
file_details = "Деталі файлу"
file_name = "Назва файлу"
file_size = "Розмір файлу"
file_downloads = "Завантажень"
print = "Друк"
viewing_zip = "Перегляд ZIP-файлу"
watching = "Перегляд файлу"

# Uploader

uploader = "Завантажувач"
upload = "Завантажити"
select_file = "Вибрати файл"
upload_success = "успішно завантажено!"
upload_error = "Сталася помилка під час завантаження файлу."
uploader_title = "Завантажувач файлів"
target_dir = "Цільова тека"
target_placeholder = "Залиште порожнім для /uploads/"
max_size = "Максимальний розмір файлу — 100 МБ."
select_folder = "Вибрати теку"
browse = "Огляд"
select_files = "Виберіть файли для завантаження."
uploading = "Завантаження"

# Account

username = "Ім’я користувача"
password = "Пароль"
invalid_info = "Невірне ім’я користувача або пароль."
log_in_with_marmak = "Увійти через MARMAK-акаунт&trade;"
welcome = "Привіт"
tip = "Порада"
settings_tip1 = "Щоб зберегти поточні налаштування, перейдіть до"
settings_tip2 = "та увімкніть «Не перезаписувати налаштування»."

# Admin

usage = "Використання"
disk_usage = "Використання диску"
sysinfo = "Інформація про сервер"
memory_usage = "Використання пам’яті"
system = "Система"
kernel_version = "Версія ядра"
hostname = "Ім’я хоста"

# Audio player

listening = "Відтворення файлу"
album = "Альбом"
year = "Рік"
genre = "Жанр"
album_cover = "Обкладинка альбому"

# File deletion

delete_success = "успішно видалено!"
delete_confirmation = "Ви впевнені, що хочете видалити"
delete = "Видалити"

# Errors

error = "Помилка"
not_found = "Не знайдено"
error_400 = "Клієнт надіслав некоректний запит. Спробуйте ще раз."
error_404 = "Ресурс не знайдено. Перевірте URL та спробуйте знову."
error_50x = "Внутрішня помилка сервера. Будь ласка, повідомте нас про це."
error_403 = "У вас немає доступу до цього ресурсу. Увійдіть як користувач з більшими правами."
no_details = "Немає доступної інформації!"
no_video = "Ваш браузер не підтримує елемент відео."
no_audio = "Ваш браузер не підтримує елемент аудіо."
upload_parse_error = "завантажено, але не вдалося розібрати відповідь."
upload_failed_status = "не вдалося завантажити зі статусом"
upload_failed_network = "завантаження не вдалося через помилку мережі."
error_occured = "Виникла помилка:"
error_deleting = "Сталася помилка під час видалення файлу."
directory_not_empty = "Ця тека не пуста!"

# Generic UI strings

ok = "OK"
cancel = "Скасувати"
others = "інші"
